### ISSUE TITLE
[Bug] Can't use language variations

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/language-switcher#10]
# Bug report

### What I did

Followed the instructions to setup the language switcher and enabled the following locales: `en, it, ro and pt_PT`. 

### What I expected to happen

Be able to change to any of those languages.

### What happened

- `en, it and ro` work fine 🟢 
- `pt_PT` (and any locale variation, like en_US or similar) will throw a 404 not found 🔴 

### What I've already tried to fix it

Niente

**Comment by promatik** [comment]
Fixed with #12.
