### ISSUE TITLE
[Discussion] showing a `Language` dropdown

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/language-switcher#11]
I was playing with the package configuration options. 

I realized I have 2 options:
- show only the flag
- show the flag and the label

And I thought What if I want to show like `Language` (a string), no flags nothing, so I set the `flags` to false, and the `main_label` to false too. 

It show only the dropdown arrow:
![image](https://github.com/Laravel-Backpack/language-switcher/assets/7188159/5d81aa88-7f2e-444c-b522-8701611247cc)

I was expecting something like:
![image](https://github.com/Laravel-Backpack/language-switcher/assets/7188159/2b271931-6198-4170-aeee-a5858e40b612)

I'd prefer to show the flags too, but only when I open the language picker. At the moment there is an entanglement between the picker options, and the dropdown "placeholder". 

I am not sure if we should do something about this, what do you guys think ?

**Comment by promatik** [comment]
Fixed with https://github.com/Laravel-Backpack/language-switcher/pull/13 🙌
