### ISSUE TITLE
Cannot Change language on login page as guest, for auth users works fine.

### ISSUE THREAD

**Issue by simke92** [Laravel-Backpack/language-switcher#15]
# Bug report

### What I did
I've tried to add language-switcher option to login page.
Tabler theme login page (illustration.blade.php) i've added
`@include('backpack.language-switcher::language-switcher')`
(Styles doesnt look good but it doesnt matter now)

In Kernel, like documentation says I added `"\Backpack\LanguageSwitcher\Http\Middleware\LanguageSwitcherMiddleware::class,"` 

```
protected $middlewareGroups = [
  'web' => [
      \App\Http\Middleware\EncryptCookies::class,
      \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
      \Illuminate\Session\Middleware\StartSession::class,
      \Illuminate\View\Middleware\ShareErrorsFromSession::class,
      \App\Http\Middleware\VerifyCsrfToken::class,
      \Illuminate\Routing\Middleware\SubstituteBindings::class,
      \Backpack\LanguageSwitcher\Http\Middleware\LanguageSwitcherMiddleware::class,  // Added
  ],
```

### What I expected to happen

Dropdown showed up, i wanted to be able to change language for login page as guest.
There is no error, but i cannot manage to change language as guest.

### What happened

Language doesnt change, just refresh page with same language

### What I've already tried to fix it

From route file i tried to disable middleware
```
Route::group([
    'namespace' => 'Backpack\LanguageSwitcher\Http\Controllers',
//    'middleware' => ['web', config('backpack.base.middleware_key', 'admin'), 'throttle:60,1'],    //Disabled
], function () {
    // set locale
    Route::any('set-locale/{locale}', [LanguageSwitcherController::class, 'setLocale'])
        ->name('language-switcher.locale');
});
```
### Context to replicate the bug - Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.2.4 (cli) (built: Mar 14 2023 17:54:25) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.28.0.0

backpack/activity-log: 2.0.0
backpack/basset: 1.2.1
backpack/crud: 6.2.3
backpack/editable-columns: 3.0.2
backpack/filemanager: 3.0.4
backpack/generators: v4.0.2
backpack/language-switcher: 1.0.0
backpack/permissionmanager: 7.1.0
backpack/pro: 2.0.15
backpack/theme-tabler: 1.1.1

**Comment by promatik** [comment]
Hi @simke92!

You are totally right, this was not working outside of the admin panel.
I just **[pushed a fix](https://github.com/Laravel-Backpack/language-switcher/pull/16)** for it, it's currently in review, and will soon be merged 🙌

**Comment by pxpm** [comment]
Thanks guys. Merged and tagged 🙏
