### ISSUE TITLE
[Bug] route language switcher not defined

### ISSUE THREAD

**Issue by aa6my** [Laravel-Backpack/language-switcher#19]
# Bug report

### What I did

I try to implement language switcher at top right

### What I expected to happen

Should be the language switcher appear at top right

### What happened

getting error after follow your instruction to install
`Route [language-switcher.locale] not defined.`

### What I've already tried to fix it

not fix yet

### Context to replicate the bug - Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.1.24 (cli) (built: Oct  6 2023 09:46:19) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.24, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.24, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.24.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.0
backpack/crud: 6.2.1
backpack/generators: v4.0.2
backpack/theme-coreuiv2: 1.2.1
backpack/theme-coreuiv4: 1.1.1
backpack/theme-tabler: 1.1.1
```

![Screenshot from 2024-01-26 11-28-00](https://github.com/Laravel-Backpack/language-switcher/assets/7272163/9cba6fa4-777a-4b69-be67-f55b8f764300)

**Comment by pxpm** [comment]
Hello @aa6my 

Maybe you are disabling the language switcher route ? 

make sure `'backpack.language-switcher.setup_routes'` is set to true in the config, and that you don't have the routes/configs cached. 

Cheers
